### ISSUE TITLE
Who triggers the actions?

### ISSUE THREAD

**Issue by khuongduybui** [adam7/delugia-code#1]
OK. Great. It worked!

Now how do we go about re-run the actions on commits of upstream?

**Comment by adam7** [comment]
That's a good question, we could schedule the job to run on a regularly as well as on push, maybe once a week?

**Comment by khuongduybui** [comment]
Can we have at least it run on each new release of upstream? Like today :)

**Comment by adam7** [comment]
It's triggered on every push currently so if you ever spot a change, submit a pull request and the new version should get built

**Comment by adam7** [comment]
There is a new version available based on the latest Cascadia Code release available now on the releases page.

**Comment by Finii** [comment]
It seems you can check automatically if Cascadia Code has a new release. Like every week or so (via cronjob [1]). If it has you can create a new Delugia release based on that.

Don't know how realistic this is.

[1] https://stackoverflow.com/questions/58465057/trigger-a-github-action-when-another-repository-creates-a-new-release

**Comment by khuongduybui** [comment]
That’s not a bad idea.
