### ISSUE TITLE
Backticks broken

### ISSUE THREAD

**Issue by Sacro** [adam7/delugia-code#18]
When I'm using backticks, rather than them appearing before the letter, they appear on top
so ``` `a``` comes up as `à` instead.

**Comment by Finii** [comment]
Please make sure you use the most recent release. Verify that the font version is 1910.04.1 (look for the number in your systems font management system). This affected an old revision, see PR #11 and issue #17.

If you still have the problem we would need a screenshot, name and version of the editor you are using, and preferably screenshots of your systems font manager. For example like so:

![Screenshot from 2019-10-29 11-58-45](https://user-images.githubusercontent.com/16012374/67852940-af8e5c80-fb0d-11e9-87f9-3fd7ea5a953e.png)

**Comment by Finii** [comment]
Or like this ;-)

![Screenshot](https://user-images.githubusercontent.com/16012374/67853312-91752c00-fb0e-11e9-85cc-d2e0603d3f3a.png)

**Comment by Sacro** [comment]
Look at that, I was running `1910.04`! 

Keep up the great work!
