### ISSUE TITLE
Document the short names

### ISSUE THREAD

**Issue by onovotny** [adam7/delugia-code#2]
I'm trying to use the complete set in Terminal, but it can't seem to find it.... 

I have it installed for all users
![image](https://user-images.githubusercontent.com/1427284/66270338-30647c00-e820-11e9-8e4e-dcee290cdaae.png)

But despite setting the fontFace to what I believe the correct value to be (and trying lots of other variations), I can't seem to get Terminal to pick it up:
![image](https://user-images.githubusercontent.com/1427284/66270348-483c0000-e820-11e9-9331-c66c80f8e030.png)

Not sure if the string value is correct or if there's possibly an issue in Terminal.

**Update**: Looks like the correct value in the profiles.json is: `Delugia Nerd Font`

**Comment by adam7** [comment]
I've updated the readme to specify the font names, let me know if you think that fixes the issue.

**Comment by onovotny** [comment]
As far as I can tell, I only installed the complete version but the name is `Delugia Nerd Font`, not `Delugia Nerd Font Complete` to reference it?

**Comment by adam7** [comment]
Ah yes well spotted. I've changed the text as follows:

### How to use
You can download the patched font from the [Releases page](https://github.com/adam7/delugia-code/releases) of this repo and install them as you would any other font. Once installed the font can be referenced as `Delugia Nerd Font`. So if, for example, you want to use it in Windows Terminal you should add this line to your profiles.json

`"fontFace" : "Delugia Nerd Font",`
