### ISSUE TITLE
Include the √ character (charcode 0x221A)

### ISSUE THREAD

**Issue by emptyother** [adam7/delugia-code#20]
Noticed when I ran `yo doctor` that the checkboxes were missing. Seems Cascadia Code hasn't included this character for some reason. I have posted an issue to them to include it.. But I've also noticed this version of the font adds another checkbox character (`` with charcode 0xF00C).

I figured I could just copy that character into 0x221A in the fontforge desktop app. Could that be done by the script somehow? And should it, or should we wait for the Cascadia Code team to update their font instead? I got no idea how long it is until they start working on the symbols parts.

**Comment by Finii** [comment]
It would be easy to copy it over, after checking if it is already available or not.

0x221A is the mathematical symbol SQUARE ROOT
0xF00C is a typical checkmark Microsoft Symbol OK

![Screenshot from 2019-11-06 19-10-35](https://user-images.githubusercontent.com/16012374/68325587-037ae180-00ca-11ea-9d4a-fc420ce1f483.png)
_"Root" 0x221A_

![Screenshot from 2019-11-06 19-24-49](https://user-images.githubusercontent.com/16012374/68326422-b861ce00-00cb-11ea-9419-adf5ef15ac5f.png)
_"OK" 0xF00C_

Maybe we can include the (all) math glyphs from somewhere else, I would have expected it to be included in the complete Nerd set. I would hesitate to copy "ok" to "sqrt"...

**Comment by Finii** [comment]
Hmm, at least on Gnome the font engine searches other fonts, if a specific font does not have a wanted glyph. Here you see both Delugia and Inconsolata - _both do not have the ROOT symbol_ - on the console. The character is lent from DejaVuSans...

![Screenshot from 2019-11-06 21-54-44](https://user-images.githubusercontent.com/16012374/68337505-ef8eaa00-00e0-11ea-920b-abd03a60b8fe.png)

The Character Map shows for the selected font (Inconsolata, see top left) the font really used by the rendering engine (with a right click on the character):
![Untitled](https://user-images.githubusercontent.com/16012374/68337882-b73b9b80-00e1-11ea-8e56-0261d3e76e27.png)

So I would conclude that something else is amiss with your setup, and the missing glyph should generally not be a problem.

**Comment by Finii** [comment]
For reference the issue created by @emptyother is microsoft/cascadia-code#176

**Comment by emptyother** [comment]
> Hmm, at least on Gnome the font engine searches other fonts,

Oh, okay, I see. Windows Conhost doesn't. ConEmu doesn't (probably for the same reason). But Windows Terminal do. So you are right, it shouldn't generally be a problem.

**Comment by adam7** [comment]
This seems like something we shouldn't try and fix so unless you have any objection @emptyother I'll close it.

Thanks @Finii  as always for the comprehensive investigation 🤍
