### ISSUE TITLE
Problem with displaying glyphs in powershell

### ISSUE THREAD

**Issue by torpederos** [adam7/delugia-code#22]
Hi,
after installing poshgit, oh-my-posh and delugia code font, my powershell console still doesn't display some symbols (eg. BranchIdenticalStatusToSymbol, BranchUntrackedSymbol).
![image](https://user-images.githubusercontent.com/4268593/69381337-d4ad5f80-0cb4-11ea-850f-1f6fb5fd74df.png)

Is there any fix for my issue?

**Comment by Finii** [comment]
Which glyphs do you expect there?

The defaults are 'nothing' and a star ('*'):

![Screenshot from 2019-11-22 08-26-23](https://user-images.githubusercontent.com/16012374/69406213-d94c3500-0d01-11ea-841f-0a974a944177.png)
_JanDeDobbeleer/oh-my-posh_

So you (or someone) must have set there something.

**Comment by Finii** [comment]
Sorry. Found the right place with the definitions:

![Screenshot from 2019-11-22 08-32-01](https://user-images.githubusercontent.com/16012374/69406558-9ccd0900-0d02-11ea-847f-b1fddd66bded.png)

Hold on, checking...

**Comment by Finii** [comment]
That's 'not identical' and 'strictly equivalent'. They are not included in the complete nerd fonts:

![Screenshot from 2019-11-22 08-42-10](https://user-images.githubusercontent.com/16012374/69407485-de5eb380-0d04-11ea-8cc0-6e0be2d20a4d.png)
_Your missing glyphs marked blue_

So there is nothing we can do at this point. I would expect the glyphs to be in some math related fontset. Probably you need to install that (a specific math symbol font), and what I know PowerShell will search in other fonts if a glyph is not available in the active font. There was a discussion about font substitution in one other issue.

On my machine on a Delugia font-ed terminal it works (i.e. the fallback):

![Screenshot from 2019-11-22 09-14-44](https://user-images.githubusercontent.com/16012374/69409152-a5284280-0d08-11ea-9f45-6d21f64ff226.png)

Conclusion:
I think you just miss some font that provides math symbols. The fallback from Delugia to that font should happen automagically in PowerShell.

**Comment by torpederos** [comment]
Thank you for your explanation. I'll try to figure out how to resolve this.
