### ISSUE TITLE
\u276F character does not display on conhost.exe

### ISSUE THREAD

**Issue by LuanVSO** [adam7/delugia-code#25]
### conhost with delugia code complete set as font:
![image](https://user-images.githubusercontent.com/43626415/72195599-e0362080-33f1-11ea-8f66-91ccfed76b82.png)

### conhost with hack NF set as font:
![image](https://user-images.githubusercontent.com/43626415/72195650-2c816080-33f2-11ea-8c4d-d216245c3a79.png)

**Comment by LuanVSO** [comment]
uhm, actually this problem is with cascadia itself so i think i'm gonna close this

**Comment by Finii** [comment]
As we added ``≢`` (0u2262) and ``≣`` (0u2263) already, it is super simple to fix/workaround this.

Note that the underlying real problem is the application. It should use Uniscribe instead of GDI (see bottom of #26).
