### ISSUE TITLE
Not showing as fixed-width font

### ISSUE THREAD

**Issue by onovotny** [adam7/delugia-code#3]
Not sure what the patching is doing, but Cascadia Code shows as a fixed-width font, but Delugia does not. See how Visual Studio highlights the fixed-width ones:

![image](https://user-images.githubusercontent.com/1427284/66270439-af0de900-e821-11e9-809e-2a0c26f7f3f4.png)

**Comment by adam7** [comment]
Unfortunately I have no idea why this is the case I patch the font using Font Patcher and the default options. Any suggestions on what might be causing the issue would be super helpful.

**Comment by hanubeki** [comment]
have you tried `--mono` ?

from https://github.com/ryanoasis/nerd-fonts#font-patcher
>   -s, --mono, --use-single-width-glyphs
>                         Whether to generate the glyphs as single-width not double-width (default is double-width)

**Comment by adam7** [comment]
Thanks @hanubeki I've added that switch to the workflow command.
@onovotny Can you check if the font artifacts from this build work as expected 

https://github.com/adam7/delugia-code/runs/255214512

**Comment by adam7** [comment]
Font Patcher doesn't expose a rename parameter it uses an internal set of rules to set the name ... I guess I could rename after patching 🤔

**Comment by adam7** [comment]
This should be fixed now can you check the artifacts from this build @onovotny 

https://github.com/adam7/delugia-code/commit/da257c2243fa14f1e1d9f1892838bbfc2c0ee215/checks?check_suite_id=265837862

**Comment by adam7** [comment]
Re-opening this because my (terrible) fix just made things worse. Simply building with the --mono switch breaks so many things that it's not a good choice see #5

**Comment by adam7** [comment]
Fixed, closing. See:

https://github.com/adam7/delugia-code/issues/7#issuecomment-545421933
