### ISSUE TITLE
Relative size ratio between chars and icons

### ISSUE THREAD

**Issue by Adrian-Grimm** [adam7/delugia-code#31]
In my opinion somthing is wrong with the size ratio between normal chars and icons in that font.
Here is a smal comparsion between delugia-code and a Nerd-Font variant of "Source Code Pro":

![image](https://user-images.githubusercontent.com/5657002/74430677-aaa3ad80-4e5d-11ea-8218-cb30179d8150.png)

I think the icons in that font could be ~1.5 times bigger.

**Comment by Finii** [comment]
Lets have a closer look.

![image](https://user-images.githubusercontent.com/16012374/74434694-366c0880-4e63-11ea-948f-c5dc83662cc0.png)

Hmm, for me it looks as if the folder in SourceCodePro is too wide. More than one monospace font slot?

For further analysis I would need the glyph codes. Either tell me in 0Uxxxx notation, or maybe just copy and past the characters here in a comment.

**Comment by Adrian-Grimm** [comment]
Here is that folder font icon:
```

```
the clock
```

```
the calendar
```

```
Maybe it help... default browser font will not show those. But I tested it with the preview of this post - copy & paste is working.

I would say those icons are double size but all normal characters are mono size in SauceCodeProNerdFont.

**Comment by Finii** [comment]
Your icons come from Font Awesome:

0uF115 - fa-folder-open-o
0uF013 - fa-cog
0uF017 - fa-clock-o 

We create a strict monospaced font, and as you see below the symbols fill the allotted spaces exactly. The Nerd Font version of Caskadia on the other hand does not scale. I will try to find out the implications.

![image](https://user-images.githubusercontent.com/16012374/74628281-97daf280-5155-11ea-8f05-0932be6c648b.png)

[...] But then... Font Awesome looks different. Number of teeth on the cogwheel does not even match:
![image](https://user-images.githubusercontent.com/16012374/74629200-f30de480-5157-11ea-9aad-dd7b8a45dc84.png)
(Ok, thats not related to your problem, but interesting anyway.)

**Comment by Finii** [comment]
Side note:
Ah, Nerd Font uses the last version 4 release of Font Awesome... (4.7):
![image](https://user-images.githubusercontent.com/16012374/74632675-32403380-5160-11ea-99c6-26296b58e928.png)

**Comment by Finii** [comment]
Ah, CaskaydiaCove is available in two variants, ``monospaced`` and ``Book``:
![image](https://user-images.githubusercontent.com/16012374/74633603-3f5e2200-5162-11ea-9b67-a23bedca45e3.png)
_(Shown in Writer here)_

Here what happens in a console window, running ``vi`` with CaskaydiaCove Book:
![image](https://user-images.githubusercontent.com/16012374/74633804-c8755900-5162-11ea-98be-ae17a098d186.png)
The Folder is bigger than it's allotted space. If a character (``X`` in this example) follow the folder, it will be render both glyphs on top of each other. The black rectangle below is the cursor block which completely fills 'one space'.

This boils down to: You want to use a non monospace font in your console. We do not provide the non-monospaced variants. But to change this is but a flip of a button.

**Comment by Finii** [comment]
The book variant seems to work. Here in MSVC19:
![image](https://user-images.githubusercontent.com/16012374/74636704-d62ddd00-5168-11ea-995f-2bd091e0efc0.png)

**Comment by Finii** [comment]
@Adrian-Grimm: You can test/use the font from the PR:
Go to the [job's page](https://github.com/adam7/delugia-code/pull/32/checks?check_run_id=450093731) and open the ``artefacts`` top/right. Use the Book font. It is probably [this link](https://github.com/adam7/delugia-code/suites/462568488/artifacts/1926111).

**Comment by Adrian-Grimm** [comment]
Ah OK now I understand this issue and where the up and downsides are.

"Delugia Nerd Font Book.ttf" works perfect in my usecase:
![image](https://user-images.githubusercontent.com/5657002/74656284-1fdcee80-518e-11ea-9060-e4b113b44305.png)
The issue of overlapping is OK for those icons - one blank fix this and it looks much better as the mono spaced one

**Comment by Finii** [comment]
You're welcome. I'll pull and close.
