### ISSUE TITLE
Glyphs not rendering JUST in Powershell

### ISSUE THREAD

**Issue by isaacrlevin** [adam7/delugia-code#35]
Tried to get Delugia + Nerd Fonts installed on a new box, but I cannot get it to work in Windows Terminal Powershell. Here is PS Core
![image](https://user-images.githubusercontent.com/8878502/82267418-27449d00-9921-11ea-9b78-f33b29f3175b.png)

and PS

![image](https://user-images.githubusercontent.com/8878502/82267437-3297c880-9921-11ea-8d78-51f5a1a81acf.png)

I can open an issue in Terminal, but wanted to see if there is an easy fix for this

**Comment by Finii** [comment]
How do I set the prompt, so that the git stuff is displayed?
Plain PS seems to not have it ;)

**Comment by Finii** [comment]
This is on my Windows box.
Top image: Git bash, bottom image PowerShell. I pasted a line with relevant characters from my Linux console into both.

![Screenshot from 2020-05-19 08-04-32](https://user-images.githubusercontent.com/16012374/82290528-6cabad80-99a7-11ea-9349-3a0335bdbf1d.png)

I wonder, why is it rendering as multiple chars in your screenshots, seems the unicode stuff is not working correctly? Should be one char, maybe unknown, but multiple?

**Comment by Finii** [comment]
Hmm, this is also not working with Cascadia PL.
Copy triangular thing from CharacterMap, paste into PowerShell.

![Screenshot from 2020-05-19 08-28-29](https://user-images.githubusercontent.com/16012374/82292387-1c364f00-99ab-11ea-8bc5-695c3c3fd4bd.png)

My Windows skills erode away...

**Comment by adam7** [comment]
@isaacrlevin Are you using [oh-my-posh](https://github.com/JanDeDobbeleer/oh-my-posh) for your font theming?

**Comment by isaacrlevin** [comment]
I'm using just posh git and a custom powershell profile

**Comment by KillDozerX2** [comment]
@isaacrlevin I had the same issue, but fixed it by installing both posh-git and oh-my-posh.

**Comment by isaacrlevin** [comment]
@KillDozerX2 same issue with bot installed
![image](https://user-images.githubusercontent.com/8878502/83074050-5ac0af00-a026-11ea-8880-c1f1d72e6732.png)

**Comment by Finii** [comment]
**_Funny_**

How bad is that? PowerShell does **not** reder the glyphs when you type them, but in the error message they are shown??!

![remmina_HaskStep7_localhost:1111_2020528-4578,318722](https://user-images.githubusercontent.com/16012374/83100707-d5361100-a0b0-11ea-844d-dd271d55c26b.png)

For sure this has nothing to do with the font, but with some PowerShell peculiarity.

**Comment by Finii** [comment]
Same Window, switched to _Lucida Console_, where the extra chars are not avail:
![remmina_HaskStep7_localhost:1111_2020528-5356,564832](https://user-images.githubusercontent.com/16012374/83101037-ab311e80-a0b1-11ea-8578-06b2e71ba9e2.png)

**Comment by Finii** [comment]
Hmm, seems to work _(on my machine)_.
I never had anything special installed on that Windows box, just used it to test Delugia on Windows with VisualStudio.
Installed oh-my-posh, and voila:
![remmina_HaskStep7_localhost:1111_2020528-52614,983658](https://user-images.githubusercontent.com/16012374/83102491-e41ec280-a0b4-11ea-8d2c-f17529f4e467.png)
I don't know what the missing char in the left is, but the powerline triangular things are there.

What I did (in an admin PS window) was just:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install ConEmu
Install-Module posh-git -Scope CurrentUser
Install-Module oh-my-posh -Scope CurrentUser
Install-Module -Name PSReadLine -Scope CurrentUser -Force -SkipPublisherCheck
Set-ExecutionPolicy Bypass -Scope Process -Force; Import-Module oh-my-posh
Set-Prompt
```

I reckon ConEmu is not needed, but it was in the [installation manual](https://github.com/JanDeDobbeleer/oh-my-posh).

**Comment by Finii** [comment]
Ah, with Delugia Complete we also see what that strange glyph in the left is:
![remmina_HaskStep7_localhost:1111_2020528-54548,174398](https://user-images.githubusercontent.com/16012374/83103736-95265c80-a0b7-11ea-9229-4ad777743424.png)

Can you @isaacrlevin make it work for you with these hints?

**Comment by Finii** [comment]
Git stuff also works ;)
![remmina_HaskStep7_localhost:1111_2020528-55246,906897](https://user-images.githubusercontent.com/16012374/83104127-61980200-a0b8-11ea-9514-6266b10fccfa.png)

**Comment by isaacrlevin** [comment]
Doesn't work, however the glyph is there in character map and can be pasted into terminal. I assume the encoding on my profile is messed up but it works in ps core

![image](https://user-images.githubusercontent.com/8878502/83172854-0d4b4d00-a0cd-11ea-8d90-03a0dc9fc034.png)

**Comment by Finii** [comment]
I assume the issue is 'solved' by declaring it an issue of your setup?
I'm quite at a loss what happens here.

Please feel free to reopen it, if you think we can do something. It sounded like you now think it can be a problem of your setup.
