### ISSUE TITLE
Missing Icon ⚡

### ISSUE THREAD

**Issue by viceice** [adam7/delugia-code#38]
**Delugia**
![image](https://user-images.githubusercontent.com/1798109/86577984-608da680-bf7b-11ea-81f5-965ef66f15d5.png)

**Hack**
![image](https://user-images.githubusercontent.com/1798109/86577993-64b9c400-bf7b-11ea-8740-d72f3095eac5.png)

**System**
Windows Server 2016 with cmder v1.3.15

**Comment by Finii** [comment]
Could you copy and past that flash thing here in a comment?
Then I do not need to search it.

**Comment by Finii** [comment]
It is not in _Delugia Nerd Font_, but in _Delugia Nerd Font Complete_:

![zap](https://user-images.githubusercontent.com/16012374/86579073-19a0b080-bf7d-11ea-8370-d90c84f06d00.png)

Do you have a reason why it should also be in the small-as-possible ;) non-complete font?
I assume it works with _Complete_ for you?

**Comment by viceice** [comment]
Strange, windows terminal simply doesn't render the glyph 🤔 
![image](https://user-images.githubusercontent.com/1798109/86579107-232a1880-bf7d-11ea-9222-4a595c1b2649.png)

![image](https://user-images.githubusercontent.com/1798109/86579164-34732500-bf7d-11ea-940c-ee9ed291755a.png)

**Comment by viceice** [comment]
> It is not in _Delugia Nerd Font_, but in _Delugia Nerd Font Complete_:
> 
> ![zap](https://user-images.githubusercontent.com/16012374/86579073-19a0b080-bf7d-11ea-8370-d90c84f06d00.png)
> 
> Do you have a reason why it should also be in the small-as-possible ;) non-complete font?
> I assume it works with _Complete_ for you?

Not yet tested `complete`, will do now.

**Comment by viceice** [comment]
Works with complete, thanks.

Usage: `oh-my-posh` with `Paradox` theme in powershell 5+

**Comment by Finii** [comment]
Added 'high voltage' in the [newest release](https://github.com/adam7/delugia-code/tree/v2007.01) even to the basic font.
See commit 5f152229.

**Comment by viceice** [comment]
Thanks, using complete now and maybe try the basic font in future. 😁
