### ISSUE TITLE
Error in download script and request

### ISSUE THREAD

**Issue by lfom** [adam7/delugia-code#40]
Thanks for your [post](https://admcpr.com/automating-the-patching-of-cascadia-code-to-include-nerd-fonts/) and the repo. Although the README does not explain how to actually patch the fonts, your post and (hidden) workflow helped a lot. I think there is an error in the [script that downloads the source fonts](https://github.com/adam7/delugia-code/blob/master/download-source-fonts.sh#L6-L7) for patching tho, two files aren't download correctly, these two lines are missing `?raw=true` so they would be downloaded correctly.

I also would like to ask if I can create a repo based on yours with a shell script to patch any font. Cloning the whole Nerd Fonts just to patch a few fonts seems like an overkill.

Regards

**Comment by Finii** [comment]
Sorry, I'm out of office for another 2 weeks and can not look into this now.

**Comment by adam7** [comment]
Hi @lfom Glad this was of some use to you, if you'd like to submit a pr for the script changes I'd be very happy :) 
Feel free to create away, I must add a license to this repo to make it more obvious that everyone's free to do that.

**Comment by lfom** [comment]
PR sent, I will wait for the license. Thanks again.

**Comment by adam7** [comment]
You're welcome, MIT license is in place now so I'm closing this
