### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by adam7** [adam7/delugia-code#41]
Choose an appropriate license (needs to be compatible with cascadia) and add it.

**Comment by lfom** [comment]
From [what I have read](https://github.com/microsoft/cascadia-code/blob/master/LICENSE), Microsoft uses the SIL Open Font License v1.1, so you might want to add the same license to the distributed delugia-code files (as requested in the license, btw), and perhaps a MIT license for the other files in this git.

**Comment by adam7** [comment]
MIT license added https://github.com/adam7/delugia-code/commit/9a647276bff9b92d5ba115977d9c73078947e52e
