### ISSUE TITLE
Update to 2008.25

### ISSUE THREAD

**Issue by electronic-dk** [adam7/delugia-code#43]
There's been a new cascadia code release - 2008.25 https://github.com/microsoft/cascadia-code/releases/tag/v2008.25
Would be great to have delugia code update as well.

P.S. Thank you for the font, it's my primary in Windows Terminal

**Comment by Finii** [comment]
Please find it here: https://github.com/adam7/delugia-code/releases/tag/v2008.25

Let us know if you find any problems (I just published it out of the automated box, no testing).

**Comment by Finii** [comment]
Btw, it does not use the new weighted fonts.
And thanks for hinting the new Cascadia Code rev :-)
