### ISSUE TITLE
Include light font weight in Delugia

### ISSUE THREAD

**Issue by offero** [adam7/delugia-code#45]
Terminal config: 

 ```
           "fontFace" : "Delugia Nerd Font",
            "fontWeight": "light",
            "fontSize" : 10,
```

Results in bold font

**Comment by Finii** [comment]
There is no Delugia Nerd Font light.
Which 'Terminal' are you using, that you can select 'light'? I can't.

Usually you can select **bold** or _italic_ even if not supplied by the font, but I never heard of an autogenerated light.

![Screenshot from 2020-09-28 08-35-43](https://user-images.githubusercontent.com/16012374/94398368-b54d5180-0165-11eb-9bc9-b58a2c3b1e7c.png)

**Comment by offero** [comment]
I'm using the latest Cacadia Code PL

Terminal: https://github.com/microsoft/terminal

Settings: 

```
            "fontFace" : "Cascadia Mono PL",
            "fontWeight": "light",
            "fontSize" : 10,
```

![image](https://user-images.githubusercontent.com/4681330/94448467-ed11c480-0178-11eb-941c-43cc0045e9b9.png)

**Comment by Finii** [comment]
For questions about Cascadia Code, please head over to https://github.com/microsoft/cascadia-code.

If you open Delugia in your font settings dialog, note that there is no _light_ or other weights, just _regular_.

![Capture](https://user-images.githubusercontent.com/16012374/94469699-d72af080-01c6-11eb-9ff5-09a75270c2b6.PNG)

I guess you manually typed in `light` in the terminal settings file?

**Comment by offero** [comment]
Gotcha. Consider this issue a request to include the light variant then.

**Comment by Finii** [comment]
In fact I noticed this would be easy (while working on Artur's PR).
What shall we do? All (now 5) fonts also in _light_?
Where to end, there are 5 weights for each ... :grimacing:

**Comment by Finii** [comment]
Explanation: I think we can not handle the multi-weight font files; either because a `fontforge` limitation or because limited know how to operate that on my side. But we can generate dedicated files for each weight, as Microsoft does in its `static/` subdir.

**Comment by adam7** [comment]
I think you're right @Finii we should generate all the fonts 😬

**Comment by Finii** [comment]
I guess this can be closed? Please reopen if this is still an issue with release `v2105.24.2`.
