### ISSUE TITLE
VSCode: wrong display 3 backtick characters 

### ISSUE THREAD

**Issue by thuandt** [adam7/delugia-code#5]
New font version
![image](https://user-images.githubusercontent.com/847996/66697974-61ebb480-ed04-11e9-974d-c1844a77504c.png)

Old font version
![image](https://user-images.githubusercontent.com/847996/66698095-3cab7600-ed05-11e9-9473-02f421b78bfd.png)

**Comment by Zireael** [comment]
I have the same issue. The backtick **`** used in JavaScript for string interpolation has no 'width' and is displayed on top of the next character.

**Comment by adam7** [comment]
Can you check if the version from this build fixes the issue?

https://github.com/adam7/delugia-code/runs/255214512

**Comment by thuandt** [comment]
@adam7 It's not working

**Comment by khuongduybui** [comment]
Uhmmm it's even worse.
Let's just fix one backtick first:
![image](https://user-images.githubusercontent.com/831343/66882040-ec4b4700-ef96-11e9-8f52-85934d5f2d5a.png)

**Comment by khuongduybui** [comment]
I bisected all the way back, this is the last-known-good version: https://github.com/adam7/delugia-code/commit/562eb8202b02100375ec0247c187ad81acbf6efc/checks?check_suite_id=245257563

**Comment by adam7** [comment]
@khuongduybui  So that's the last build before the latest version of Cascadia was released

**Comment by khuongduybui** [comment]
Correct. But I checked the latest version of upstream and it does not have that issue (as you can see in the screenshot)
