### ISSUE TITLE
Generate Delugia font for Cascadia Mono PL

### ISSUE THREAD

**Issue by ArturDorochowicz** [adam7/delugia-code#50]
@adam7 Would you be open to extending the project to produce a Delugia font from Cascadia Mono?

Cascadia Mono is the version of Cascadia Code without ligatures. Supporting it may be useful for those environments that don't allow disabling ligatures (e.g. Windows Terminal).

I have a commit with these changes here: https://github.com/ArturDorochowicz/delugia-code/commit/a5ac037f5630df6038227c1bd38127bfc3da616b and I could open a PR if you're OK with this.

**Comment by Finii** [comment]
Hej Artur!

> These three faces are generated:
> 
>    Delugia Nerd Font Powerline Basic glyphs, monospaced font
>    Delugia Nerd Font Complete All Nerd Fonts glyphs, monospaced font
>    Delugia Nerd Font Book All Nerd Fonts glyphs, proportional font (not recommended for coding/console)

We already generate monospaced fonts. How would the fonts gerenated from Cascadia Mono differ? Can you post an image for comparison?

Thanks, Fini

**Comment by Finii** [comment]
Duh, .... it has no ligatures.

Sorry, I need more :coffee:, its 6 oclock in the morning here ;-)

So they should not be called _Mono_ but _NonLigature_ or something?

**Comment by ArturDorochowicz** [comment]
> Duh, .... it has no ligatures.

Yes, no ligatures. Here's a screenshot from Windows Terminal with the results of the proposed change ("Mono" version at the bottom).
![Capture](https://user-images.githubusercontent.com/482931/107665783-147fae80-6c8e-11eb-86b1-c8c7a6306b27.PNG)
 
> So they should not be called _Mono_ but _NonLigature_ or something?

Up to you. I said Mono because the original is called Cascadia *Mono*.

**Comment by Finii** [comment]
Hmm, the ligatures seem to be correct (i.e. 2 spaces wide).
You are not complaining that the ligatures are rendered wrongly, right?

I believe you do not like the (to have) ligatures but the characters of the font and PowerShell is not giving you options?

(I have looked at your commit and it looked good, btw).

**Comment by adam7** [comment]
@Finii Cascadia now includes a specific ligature-free version of Cascadia called CascadiaMono in the release zip file. @ArturDorochowicz would like to bundle that into so we'd have `Delugia.Mono.Nerd.Font.ttf` etc.
Agree the commit looks good from a quick review, I'd be happy to get a PR for this 👍

**Comment by Finii** [comment]
:+1: (note some comments in Arturs commit, but that is negligible)

**Comment by ArturDorochowicz** [comment]
> @ArturDorochowicz would like to bundle that into so we'd have `Delugia.Mono.Nerd.Font.ttf` etc.
@adam7 I don't quite follow. You want dots instead of spaces in the file name?

**Comment by Finii** [comment]
The blancs become dots automatically on publish ;)

**Comment by Finii** [comment]
Merged - closing.
