### ISSUE TITLE
Update Delugia Code with newest version?

### ISSUE THREAD

**Issue by DennisGaida** [adam7/delugia-code#52]
I love using Delugia Code since it is currently the only "working" version of Cascadia Code with all Nerd Fonts patched.

The [Nerd-Fonts font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/CascadiaCode) has rendering issues (with my setup). The official PL-version of Cascadia Code does not include all Nerd Fonts, but only the Powerline Symbols.

So any chance of updating Delugia Code with the newest font version. Currently that is 2102.03: https://github.com/microsoft/cascadia-code/releases/tag/v2102.03 and it was just released yesterday - maybe this can also automated with a Github action?

**Comment by Finii** [comment]
Please have a look at https://github.com/adam7/delugia-code/releases

**Comment by Finii** [comment]
> maybe this can also automated with a Github action?

It actually is possible, and we discussed it some aeons ego. And for some reason I can't remember we decided against it.
I think even the needed changes were in that discussion.

If **that** is your issue, please reopen.

**Comment by Finii** [comment]
Oh, this I missed.

Seems since commit 73324cc73cf5d160fa9625a2c7a9ed54c93bcf86 we already have automated re-releases.
It checks once every 24h.

**Comment by DennisGaida** [comment]
> Seems since commit [73324cc](https://github.com/adam7/delugia-code/commit/73324cc73cf5d160fa9625a2c7a9ed54c93bcf86) we already have automated re-releases.
> It checks once every 24h.

Whoops, then sorry for the issue! A bit premature. I was just so excited - Delugia Code **is** still better than the Nerd Fonts version or the offical MS version.

**Comment by Finii** [comment]
Do you have any details what is different from Nerd Fonts' version?
We started before they did, so I did not really follow that too closely. And had one bug in font-patcher fixed upstream after fixing it for Delugia.
