### ISSUE TITLE
lowercase letters in cursive don't match up with those in cascadia code

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [adam7/delugia-code#65]
### Issue
The lowercase letters in Delugia Code Italic (Cursive) don't match up with their counterparts in Cascadia Code Italic. 
### Reason
I think this improvement made would be beneficial to many Delugia Code users who want consistency between Delugia and Cascadia (including me!).
### Screenshots
**Cascadia Code**
![image](https://user-images.githubusercontent.com/79387351/127464855-5ebc621e-07a5-4e6c-a59c-16488c1007c9.png)

**Delugia Code**
![image](https://user-images.githubusercontent.com/79387351/127464763-1c1b7404-972a-4af4-aaa6-f16d174b83d2.png)

**Comment by Finii** [comment]
Cascadia Code has in fact two italic faces (one reachable via open type stylistic set iirc).
Will investigate on the weekend.

**Comment by Finii** [comment]
From your screenshot the lower case `f` and `r` are easily discernible.

As I already pointed out, the curly version that you attribut to Cascadia is not the normal Cascadia glyph but only in when a stylistic set is activated (screenshot of Cascadias landing page):

![image](https://user-images.githubusercontent.com/16012374/127809576-9e1ff7da-aefb-46be-86f4-ff0b3f03cdad.png)

I believe this has been changed with the newest (2106.17) release of Cascadia related to Issue https://github.com/microsoft/cascadia-code/issues/468 (for example have a look at comment https://github.com/microsoft/cascadia-code/issues/468#issuecomment-850297845).

So I think the _consistency_ is already existing, but you do not compare against the newest Cascadia Code release.

(I did not check if `SS01` is available in Delugia, but that would be another story anyhow. As we do not touch existing glyphs at all, I can not imaging that we deviate in that regard).

**Comment by Finii** [comment]
Check here https://github.com/microsoft/cascadia-code/releases/tag/v2106.17 for features and changes of the 2106.07 Cascadia release... ;)
_(forgot to include the link in the comment above)_

**Comment by Finii** [comment]
The SS01 is embedded also in Delugia.

You need to activate SS01 if you like the more curly versions more.
This is consistent with Cascadia.

Example (note ticked Stylistic Set 1 in the dialog to the right):

![image](https://user-images.githubusercontent.com/16012374/127815011-d43631bc-60a7-4dda-8eba-11aeb12fb0ed.png)
