### ISSUE TITLE
Allow installations with Chocolatey

### ISSUE THREAD

**Issue by maicol07** [adam7/delugia-code#67]
It seems Scoop [has been abandoned](https://github.com/lukesampson/scoop/issues/2609), so the bucket should be available to install with Chocolatey, which seems to be actively mantained

**Comment by Finii** [comment]
I think Scoop is still usable, is it not?

The only thing missing is an update in https://github.com/matthewjberger/scoop-nerd-fonts for the latest fonts.
Maybe someone is willing to create the new `.json` files and crate a PR there.

With Chocolatey (which I never used, but like from _His Dark Materials_) I have no clue. Someone versed in that should create a MR somewhere?

One problem can be that we automagically create new versions, but who will maintain the installer stuff?

I usually just take the zip archive, unzip it and throw the contents into the `fonts` folder. Done.

**Comment by maicol07** [comment]
You can look at Nerd Font's package: https://community.chocolatey.org/packages/nerd-fonts-3270

**Comment by adam7** [comment]
Chocolatey and/or Winget would be super nice but both require a script, an msi or an exe. 
Creating those shouldn't be the responsibility of this repo, I'd recommend closing this.

**Comment by adam7** [comment]
This is the same way that nerd-fonts works btw, there is a separate chocolatey-nerd-fonts repo https://github.com/sumo300/chocolatey-nerd-fonts

**Comment by rashil2000** [comment]
> It seems Scoop [has been abandoned](https://github.com/lukesampson/scoop/issues/2609), so the bucket should be available to install with Chocolatey, which seems to be actively mantained

Scoop is active again (see https://github.com/ScoopInstaller/Scoop/issues/4456). Delugia is [already present](https://github.com/matthewjberger/scoop-nerd-fonts/search?q=delugia) in the known nerd-fonts Scoop bucket.

**Comment by adam7** [comment]
@rashil2000 Thanks for letting us know, I'm closing this again.

**Comment by rashil2000** [comment]
That's alright but wasn't this issue about request to add to Chocolatey? Neither Chocolatery nor the aforementioned repo - https://github.com/sumo300/chocolatey-nerd-fonts - have Delugia (yet).

**Comment by adam7** [comment]
It was but Chocolatey support shouldn't be a concern for this repo, see my comments above for why.

**Comment by rashil2000** [comment]
Thanks for the info, I have created a request in the relevant repo - https://github.com/sumo300/chocolatey-nerd-fonts/issues/3

**Comment by rashil2000** [comment]
All 5 variants of Delugia are now available on Chocolatey 🎊

**Comment by Finii** [comment]
I believe we should add the Chocolatey install to the `README.md`, esp because the scoop is 'probably not working'. And Chocolatey has the cooler name ;). But as non-Windows person I have no clue how one uses that.

Maybe @rashil2000 you could sketch out how users can install Choco and then Delugia, and we add that to the docu?

**Comment by rashil2000** [comment]
> esp because the scoop is 'probably not working'. 

Sorry I didn't get you, what is not working?

> Maybe @rashil2000 you could sketch out how users can install Choco and then Delugia, and we add that to the docu?

The installation for Chocolatey is best explained in their own docs - https://chocolatey.org/install - users can just refer it. Afterwards it's really simple commands - https://community.chocolatey.org/packages?q=delugia: 

![image](https://user-images.githubusercontent.com/46838874/167455886-ac801a2e-9ded-40f7-9533-fa177577bf06.png)

**Comment by adam7** [comment]
@rashil2000, @Finii was just asking for choco install instructions in the readme. I've added some

**Comment by rashil2000** [comment]
Oh.

> Scoop installation needs to be repaired after a naming change, I guess.

Also this line can be removed. Scoop is (or was) never undergoing a naming change.

**Comment by Finii** [comment]
> > Scoop installation needs to be repaired after a naming change, I guess.
> 
> Also this line can be removed. Scoop is (or was) never undergoing a naming change.

Well, that line was/is mine. I mean the Delugia naming change. Iirc the scoop stuff has some hard coded filenames or something, and we changed that here.

**Comment by Finii** [comment]
Scoop seems to have been updated... Will remove the comment.

Thanks for the hint.
