### ISSUE TITLE
Delugia Nerd Font Complete vs Delugia Font in Console

### ISSUE THREAD

**Issue by neradp** [adam7/delugia-code#68]
Hi i can use Delugia Nerd in cmd or powershell console, but not the latest Delugia. It is a bug or normal behaviour ?

**Comment by Finii** [comment]
Hej!
What does "can not use" mean? Maybe you can be a bit more specific and/or add a screenshot? 
Good would also be the version of Delugia you try. 

Fini

**Comment by neradp** [comment]
![obrázok](https://user-images.githubusercontent.com/7801598/136211457-8cc91160-3c72-4ed5-87be-9f5da8862325.png)

I cannot select Delugia font on console properties. Im windows user. I do the same installation process for both of them.

**Comment by Finii** [comment]
Thank you. Will have a look.

**Comment by yutsuo** [comment]
Can confirm. Same thing happens with me.

using Windows 11.

![image](https://user-images.githubusercontent.com/43550162/141789380-d5b4bcb9-6e75-4355-9e10-90bcfa4ce363.png)

**Comment by Finii** [comment]
I tried `cmd` and one of the various power shell things, and it indeed does not show up. Will examinate.

**Comment by Finii** [comment]
The panose proportion flag is missing, lets see how to fix it...

**Comment by Finii** [comment]
New versions released. Please use one of `delugia-mono-complete.zip` or `delugia-mono-powerline.zip`.
Please report any issues with the new release (or when you are happy ;)
