### ISSUE TITLE
Is this glyph being displayed too small?

### ISSUE THREAD

**Issue by trallnag** [adam7/delugia-code#69]
## Introduction

Hello, first: Thanks for the project. I think it is a great idea to have many more decentralized but also automated projects turning fonts into nerd fonts instead of a single big one. And this shows how it can be done

## Question

I have noticed that basically all nerd font specific glyphs are being displayed very small compared to official unicode glyphs. It looks like all glyphs are occupying a single "width".

![image](https://user-images.githubusercontent.com/24834206/136467408-e3aa7ded-129f-4be9-9bdd-0a9812dbdc5d.png)

```
echo -e "\uf015HALLO\n🚀HALLO"
```

Is this expected? Is it the same for other users?

## Environment

* Windows 10
* Windows Terminal

**Comment by trallnag** [comment]
Just as wished 👍 

![image](https://user-images.githubusercontent.com/24834206/136555107-0580bf98-f0b7-4a44-87d3-e699c069d2cb.png)

**Comment by Finii** [comment]
That is the reason we decided to have different naming scheme than Nerd Fonts; to be free to handle stuff as we/our users see fit.

I close this, please reopen if you think something is still amiss.

Thanks for the report.
