### ISSUE TITLE
Font name isn't updated

### ISSUE THREAD

**Issue by onovotny** [adam7/delugia-code#7]
After #6, the font name isn't showing up correctly in Windows:

![image](https://user-images.githubusercontent.com/1427284/66842577-82e91b00-ef39-11e9-91eb-672ec0ce1689.png)

The full name is "Delugia Nerd Font" and it does show up that way in Visual Studio.

![image](https://user-images.githubusercontent.com/1427284/66842679-aa3fe800-ef39-11e9-883f-cb168b2c0661.png)

Looks like a disconnect between the Windows display name and the font name?

**Comment by onovotny** [comment]
Hmm, it's worse than that. VS shows it as `Delugia Nerd Font` but for VS Code you need to use `CascadiaCode Nerd Font Mono`.

**Comment by adam7** [comment]
Can you confirm this is fixed now @onovotny

**Comment by onovotny** [comment]
The latest build from master appears to show the correct name in Windows and VS. It also shows as monospace:

![image](https://user-images.githubusercontent.com/1427284/67393218-90b92480-f567-11e9-9cd9-c03a658fdbc3.png)

![image](https://user-images.githubusercontent.com/1427284/67393246-a0386d80-f567-11e9-9863-d4564b75e72f.png)

**Comment by adam7** [comment]
Awesome closing
