### ISSUE TITLE
MacOs 

### ISSUE THREAD

**Issue by eddyekofo94** [adam7/delugia-code#70]
How do I install this on MacOs? thanks

**Comment by Finii** [comment]
MacOS is super easy :-)
At least according to DuckDuckGo (which found the following links), I have no Mac.

1. Find the font-set of **Delugia** that fits your needs.
Read https://github.com/adam7/delugia-code#which-font-faces-are-available for information.
1. Then download the set's `zip` archive from https://github.com/adam7/delugia-code/releases .
1. Unzip the downloaded archive. (https://support.apple.com/guide/mac-help/zip-and-unzip-files-and-folders-on-mac-mchlp2528/mac)
1. Install (probably) all font files in the extracted archive. (https://support.apple.com/en-us/HT201749 or https://www.xda-developers.com/how-to-install-fonts-mac/)
1. Probably restart the program you want to use the fonts in.

Please close if this answered your question, or provide more details.

**Comment by eddyekofo94** [comment]
Thanks. Got it working
