### ISSUE TITLE
Delugia Nerd Font can't work in powershell

### ISSUE THREAD

**Issue by pheotry** [adam7/delugia-code#74]
When I use ''Delugia PL"(installed with scoop)，But Delugia PL can work well in other Console (Windows Terminal)

Warning:
can't found font "Delugia PL"
please select "Cosoloas"
please  install font of lack or select other

**Comment by Finii** [comment]
How do you install via scoop?

Is the font name spelling correct? Am on mobile right now and can not check. Plus: Would be better to provide a screenshot (of your settings and the error message). 

Probably you need the 'mono' version (i.e. `Delugia Mono PL`)? 

`sudo scoop install Delugia-Mono-Nerd-Font`

**Comment by adam7** [comment]
No response so I'll close this
